@startuml
component "Vue\nFrontend HTML/CSS/JS" as Vue #81C784
component "Middleware\nValidators (Joi)" as Validators #FF8A65
component "Contrôleur\nTaskController/UserController" as Controleur #64B5F6
component "Modèle\nTask/User" as Modele #FFD54F

note right of Validators
  userValidator.js
  validate(schema)
  Validation avant contrôleur
end note

Vue -down-> Validators : Requêtes HTTP
Validators -down-> Controleur : Données validées
Controleur -down-> Modele : Manipule
Modele -up-> Controleur : Données
Controleur -up-> Validators : Réponses
Validators -up-> Vue : Réponses JSON
@enduml
